# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/UTCN/An3Sem1/SSC/ProiectFinal/ProjectSSC/ProjectSSC.srcs/sources_1/ip/clk_wizard/clk_wizard.xci
# IP: The module: 'clk_wizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UTCN/An3Sem1/SSC/ProiectFinal/ProjectSSC/ProjectSSC.srcs/sources_1/ip/clk_wizard/clk_wizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/UTCN/An3Sem1/SSC/ProiectFinal/ProjectSSC/ProjectSSC.srcs/sources_1/ip/clk_wizard/clk_wizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/UTCN/An3Sem1/SSC/ProiectFinal/ProjectSSC/ProjectSSC.srcs/sources_1/ip/clk_wizard/clk_wizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/UTCN/An3Sem1/SSC/ProiectFinal/ProjectSSC/ProjectSSC.srcs/sources_1/ip/clk_wizard/clk_wizard.xci
# IP: The module: 'clk_wizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UTCN/An3Sem1/SSC/ProiectFinal/ProjectSSC/ProjectSSC.srcs/sources_1/ip/clk_wizard/clk_wizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/UTCN/An3Sem1/SSC/ProiectFinal/ProjectSSC/ProjectSSC.srcs/sources_1/ip/clk_wizard/clk_wizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/UTCN/An3Sem1/SSC/ProiectFinal/ProjectSSC/ProjectSSC.srcs/sources_1/ip/clk_wizard/clk_wizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
